### ISSUE TITLE
Use configs for docker image configuration

### ISSUE THREAD

**Issue by alejandro-colomar** [alejandro-colomar/www#23]
Right now, the configuration of the nginx web server is hardcoded into the docker image.  docker configs should be used for that

**Comment by secobau** [comment]
Right now we are using Dockerfile to download the repo and copy the necessary files.

Maybe we should consider the possibility that Dockerfile just used the repo that is locally available. That would spare a second download and also make available the possibility to build the image while offline. This last feature could be useful for building ARM images or in cases where being online is not an option.
