### ISSUE TITLE
/srv shouldn't be hardcoded into the docker image

### ISSUE THREAD

**Issue by alejandro-colomar** [alejandro-colomar/www#25]
https://github.com/alejandro-colomar/www/blob/4bd3dece460ad802cebc90267f07018b8bad9808/etc/docker/build/Dockerfile#L26

`--volume` should be used in the docker-compose instead.

Need [secobau/docker-aws](https://github.com/secobau/docker-aws) support

**Comment by secobau** [comment]
You need to set up an external volume. It can be an NFS mount, an AWS S3 bucket or even a folder in the local host. This last approach is not recommended at all because it binds the mount to that specific host.

**Comment by alejandro-colomar** [comment]
We will first use a folder in the local host.  When that works, we will use an NFS.

But the blue/green deployment needs to be aware of it somehow.

**Comment by alejandro-colomar** [comment]
Or... given that the html source is subject to the same version control than the docker image, it can be embedded in the image.
